/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>
#include <math.h>
#include <windows.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int __thiscall sub_40100F(_DWORD);                                 // weak
_DWORD __stdcall sub_40101E(_DWORD, _DWORD, _DWORD, _DWORD, char); // weak
int sub_401070();
int sub_4010B0();
int sub_4010F0();
int sub_401130();
int sub_401180();
void __cdecl sub_4011D0(); // idb
size_t __cdecl sub_401510(char* Str);
char* __cdecl sub_401910(char* Format, char a2);
char* sub_401A30();
UIWindow* __thiscall sub_401C40(UIWindow* this, struct UIWindow* a2, int a3, int a4, int a5, bool a6);
int __thiscall sub_401CC0(UIWindow* this, HWND a2, unsigned int a3, unsigned int a4, int a5);
int __cdecl sub_401DB0(int a1);
UIMgr* __thiscall sub_401FF0(UIMgr* this, char a2);
ModuleMgr* __thiscall sub_402070(ModuleMgr* this, char a2);
NodeMgr* __thiscall sub_4020F0(NodeMgr* this, char a2);
void __cdecl sub_4021C0(float a1);
_DWORD* __thiscall sub_402280(_DWORD* this);
// int __cdecl atexit(void (__cdecl *)());
// void *__cdecl operator new(unsigned int); idb
// void __cdecl operator delete(void *); idb
// size_t __cdecl strlen(const char *Str);
// int _CxxFrameHandler(void); weak
// double __cdecl sqrt(double x); idb
void sub_402700();
int SEH_401510();
int SEH_401A30();
// char *__cdecl strdup(const char *Src);
// int __cdecl findnext(int, struct _finddata_t *);
// int sprintf(char *Dest, const char *Format, ...);
// int __cdecl findfirst(const char *, struct _finddata_t *);
// int __cdecl findclose(int);
// int __cdecl vsprintf(char *Dest, const char *Format, va_list Args);
// BOOL __stdcall ShowWindow(HWND hWnd, int nCmdShow);
// HMENU __stdcall GetMenu(HWND hWnd);
// HMENU __stdcall LoadMenuA(HINSTANCE hInstance, LPCSTR lpMenuName);
// HMENU __stdcall GetSubMenu(HMENU hMenu, int nPos);
// _DWORD __thiscall UIWindow::UIWindow(UIWindow *__hidden this, struct UIWindow *, _DWORD, _DWORD, _DWORD, bool); weak
// _DWORD __thiscall UIWindow::processMessage(UIWindow *__hidden this, HWND, unsigned int, unsigned int, _DWORD); weak
// void __thiscall Module::menuPlugins(Module *__hidden this, struct MenuPlugin *, HMENU); weak
// struct Module *__thiscall ModuleMgr::loadModule(ModuleMgr *__hidden this, char *); weak
// _DWORD __thiscall UIMgr::~UIMgr(UIMgr *__hidden this); weak
// _DWORD __thiscall ModuleMgr::~ModuleMgr(ModuleMgr *__hidden this); weak
// _DWORD __thiscall NodeMgr::~NodeMgr(NodeMgr *__hidden this); weak
// _DWORD __thiscall RectArea::RectArea(RectArea *__hidden this, _DWORD, _DWORD, _DWORD, _DWORD); weak
// void __thiscall UIFrame::setFrame(UIFrame *__hidden this, struct RectArea *); weak
// struct UIWindow *__thiscall System::createDebugStream(struct UIWindow *); weak
// void Stream::print(Stream *__hidden this, char *, ...); weak
// _DWORD __thiscall RamStream::RamStream(RamStream *__hidden this, void *, _DWORD); weak
// _DWORD __thiscall CmdStream::CmdStream(CmdStream *__hidden this, struct Stream *); weak
// bool __thiscall CmdStream::endOfCmds(CmdStream *__hidden this); weak
// bool __thiscall CmdStream::endOfSection(CmdStream *__hidden this); weak
// char *__thiscall CmdStream::getToken(CmdStream *__hidden this, bool); weak
// bool __thiscall CmdStream::isToken(CmdStream *__hidden this, char *); weak
// _DWORD __thiscall AtxDirectRouter::AtxDirectRouter(AtxDirectRouter *__hidden this, char *); weak
// void *__thiscall ModuleMgr::Alloc(ModuleMgr *__hidden this, char *); weak
// int __thiscall System::~System(_DWORD); weak
// int __thiscall System::System(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void(__thiscall* off_41515C[2])(CoreNode* this, struct AgeServer*) = {&CoreNode::genAge, &CoreNode::genAgeNode}; // weak
char* off_416520 = "OpenGL / Dolphin System";                                                                    // weak
_UNKNOWN unk_416638;                                                                                             // weak
int dword_416640 = 0;                                                                                            // weak
_UNKNOWN unk_416648;                                                                                             // weak
int dword_416AB8 = 0;                                                                                            // weak
// extern struct Stream *sysCon; weak
// extern HINSTANCE sysHInst; weak
// extern struct ModuleMgr *modMgr; weak
// extern struct System *gsys; weak


//----- (00401070) --------------------------------------------------------
int sub_401070() { return sub_4010B0(); }

//----- (004010B0) --------------------------------------------------------
int sub_4010B0() { return sub_40100F(&unk_416638); }
// 40100F: using guessed type int __thiscall sub_40100F(_DWORD);

//----- (004010F0) --------------------------------------------------------
int sub_4010F0()
{
    sub_401130();
    return sub_401180();
}

//----- (00401130) --------------------------------------------------------
int sub_401130() { return System::System(&unk_416648); }
// 41749C: using guessed type int __thiscall System::System(_DWORD);

//----- (00401180) --------------------------------------------------------
int sub_401180() { return atexit(sub_4011D0); }

//----- (004011D0) --------------------------------------------------------
void __cdecl sub_4011D0() { System::~System(&unk_416648); }
// 417498: using guessed type int __thiscall System::~System(_DWORD);

//----- (00401510) --------------------------------------------------------
size_t __cdecl sub_401510(char* Str)
{
    size_t result;        // eax
    char v2;              // al
    size_t v3;            // eax
    char* v4;             // ST80_4
    char* v5;             // eax
    char* v6;             // ST7C_4
    char v7;              // [esp+0h] [ebp-88h]
    char v8;              // [esp+0h] [ebp-88h]
    int v9;               // [esp+4Ch] [ebp-3Ch]
    CmdStream* v10;       // [esp+50h] [ebp-38h]
    struct Stream* v11;   // [esp+54h] [ebp-34h]
    AtxDirectRouter* v12; // [esp+58h] [ebp-30h]
    RamStream* v13;       // [esp+60h] [ebp-28h]
    CmdStream* v14;       // [esp+68h] [ebp-20h]

    sub_401DB0((int)"plugins");
    result = strlen(Str);
    if (result)
    {
        v2 = strlen(Str);
        sub_401910("got cmdParams [%d] : %s\n", v2);
        v14 = (CmdStream*)operator new(0x11Cu);
        if (v14)
        {
            v13 = (RamStream*)operator new(0x14u);
            if (v13)
            {
                v3 = strlen(Str);
                v11 = (struct Stream*)RamStream::RamStream(v13, Str, v3);
            }
            else
            {
                v11 = 0;
            }
            v10 = (CmdStream*)CmdStream::CmdStream(v14, v11);
        }
        else
        {
            v10 = 0;
        }
        while (!CmdStream::endOfCmds(v10) && !CmdStream::endOfSection(v10))
        {
            CmdStream::getToken(v10, 1);
            if (CmdStream::isToken(v10, "+output"))
            {
                sub_401A30();
            }
            else if (CmdStream::isToken(v10, "+plugins"))
            {
                v4 = CmdStream::getToken(v10, 1);
                sub_401DB0((int)v4);
            }
            else if (CmdStream::isToken(v10, "+direct"))
            {
                sub_401910("Creating atxDirectRouter\n", v7);
                v12 = (AtxDirectRouter*)operator new(0x14u);
                if (v12)
                {
                    v5 = CmdStream::getToken(v10, 1);
                    v9 = AtxDirectRouter::AtxDirectRouter(v12, v5);
                }
                else
                {
                    v9 = 0;
                }
                *((_DWORD*)gsys + 270) = v9;
                sub_401910("done\n", v8);
            }
            else if (CmdStream::isToken(v10, "+client"))
            {
                v6 = CmdStream::getToken(v10, 1);
                ModuleMgr::Alloc(modMgr, v6);
            }
        }
        result = CmdStream::endOfCmds(v10);
        if (!result)
            result = (size_t)CmdStream::getToken(v10, 1);
    }
    return result;
}
// 41744C: using guessed type _DWORD __thiscall RamStream::RamStream(RamStream *__hidden this, void *, _DWORD);
// 417450: using guessed type _DWORD __thiscall CmdStream::CmdStream(CmdStream *__hidden this, struct Stream *);
// 417454: using guessed type bool __thiscall CmdStream::endOfCmds(CmdStream *__hidden this);
// 417458: using guessed type bool __thiscall CmdStream::endOfSection(CmdStream *__hidden this);
// 41745C: using guessed type char *__thiscall CmdStream::getToken(CmdStream *__hidden this, bool);
// 417460: using guessed type bool __thiscall CmdStream::isToken(CmdStream *__hidden this, char *);
// 417464: using guessed type _DWORD __thiscall AtxDirectRouter::AtxDirectRouter(AtxDirectRouter *__hidden this, char
// *); 417468: using guessed type void *__thiscall ModuleMgr::Alloc(ModuleMgr *__hidden this, char *); 41746C: using
// guessed type HINSTANCE sysHInst; 41747C: using guessed type struct ModuleMgr *modMgr; 41748C: using guessed type
// struct System *gsys;

//----- (00401910) --------------------------------------------------------
char* __cdecl sub_401910(char* Format, char a2)
{
    char* result; // eax
    size_t v3;    // eax
    char Dest;    // [esp+4Ch] [ebp-404h]
    va_list Args; // [esp+44Ch] [ebp-4h]

    result = &a2;
    Args = &a2;
    if (sysCon)
    {
        if ("sysBootup")
            Stream::print(sysCon, "%s: ", "sysBootup");
        vsprintf(&Dest, Format, Args);
        result = (char*)strlen(&Dest);
        if (result)
        {
            v3 = strlen(&Dest);
            result =
                (char*)(*(int(__thiscall**)(struct Stream*, char*, size_t))(*(_DWORD*)sysCon + 56))(sysCon, &Dest, v3);
        }
    }
    return result;
}
// 417444: using guessed type struct Stream *sysCon;
// 417448: using guessed type void Stream::print(Stream *__hidden this, char *, ...);

//----- (00401A30) --------------------------------------------------------
char* sub_401A30()
{
    struct RectArea* v0; // eax
    HMENU v1;            // eax
    int v3;              // [esp+4Ch] [ebp-3Ch]
    char v4;             // [esp+50h] [ebp-38h]
    void* v5;            // [esp+60h] [ebp-28h]
    int v6;              // [esp+64h] [ebp-24h]
    struct UIWindow* v7; // [esp+68h] [ebp-20h]
    int v8;              // [esp+6Ch] [ebp-1Ch]
    int v9;              // [esp+70h] [ebp-18h]
    int v10;             // [esp+74h] [ebp-14h]
    int v11;             // [esp+78h] [ebp-10h]
    int v12;             // [esp+84h] [ebp-4h]

    RectArea::RectArea((RectArea*)&v8, 690, 32, 1260, 300);
    v5 = operator new(0x88u);
    v12 = 0;
    if (v5)
        v3 = sub_40101E(0, 0, 381943808, 0, 1);
    else
        v3 = 0;
    v6 = v3;
    v12 = -1;
    dword_416AB8 = v3;
    v0 = (struct RectArea*)RectArea::RectArea((RectArea*)&v4, v8, v9, v10, v11);
    UIFrame::setFrame((UIFrame*)dword_416AB8, v0);
    v1 = LoadMenuA(sysHInst, (LPCSTR)0x65);
    (*(void(__thiscall**)(int, const char*, char*, HMENU))(*(_DWORD*)dword_416AB8 + 80))(dword_416AB8, "DUIClearWin",
                                                                                         off_416520, v1);
    v7 = System::createDebugStream(gsys);
    (*(void(__thiscall**)(int))(*(_DWORD*)dword_416AB8 + 52))(dword_416AB8);
    ShowWindow(*(HWND*)(dword_416AB8 + 100), 1);
    return sub_401910("Basedir = %s\n", *((_DWORD*)gsys + 20));
}
// 40101E: using guessed type _DWORD __stdcall sub_40101E(_DWORD, _DWORD, _DWORD, _DWORD, char);
// 416520: using guessed type char *off_416520;
// 416AB8: using guessed type int dword_416AB8;
// 417438: using guessed type _DWORD __thiscall RectArea::RectArea(RectArea *__hidden this, _DWORD, _DWORD, _DWORD,
// _DWORD); 41743C: using guessed type void __thiscall UIFrame::setFrame(UIFrame *__hidden this, struct RectArea *);
// 417440: using guessed type struct UIWindow *__thiscall System::createDebugStream(struct UIWindow *);
// 41746C: using guessed type HINSTANCE sysHInst;
// 41748C: using guessed type struct System *gsys;

//----- (00401C40) --------------------------------------------------------
UIWindow* __thiscall sub_401C40(UIWindow* this, struct UIWindow* a2, int a3, int a4, int a5, bool a6)
{
    UIWindow* v6; // ST60_4

    v6 = this;
    UIWindow::UIWindow(this, a2, a3, a4, a5, a6);
    *(_DWORD*)v6 = off_41515C;
    return v6;
}
// 41515C: using guessed type void (__thiscall *off_41515C[2])(CoreNode *this, struct AgeServer *);
// 417418: using guessed type _DWORD __thiscall UIWindow::UIWindow(UIWindow *__hidden this, struct UIWindow *, _DWORD,
// _DWORD, _DWORD, bool);

//----- (00401CC0) --------------------------------------------------------
int __thiscall sub_401CC0(UIWindow* this, HWND a2, unsigned int a3, unsigned int a4, int a5)
{
    int i;        // [esp+54h] [ebp-Ch]
    UIWindow* v7; // [esp+5Ch] [ebp-4h]

    v7 = this;
    if (a3 == 273)
    {
        for (i = dword_416640; i; i = *(_DWORD*)(i + 8))
        {
            if (*(_DWORD*)i == a4)
            {
                ModuleMgr::Alloc(modMgr, *(char**)(i + 4));
                return UIWindow::processMessage(v7, a2, a3, a4, a5);
            }
        }
    }
    return UIWindow::processMessage(v7, a2, a3, a4, a5);
}
// 416640: using guessed type int dword_416640;
// 41741C: using guessed type _DWORD __thiscall UIWindow::processMessage(UIWindow *__hidden this, HWND, unsigned int,
// unsigned int, _DWORD); 417468: using guessed type void *__thiscall ModuleMgr::Alloc(ModuleMgr *__hidden this, char
// *); 41747C: using guessed type struct ModuleMgr *modMgr;

//----- (00401DB0) --------------------------------------------------------
int __cdecl sub_401DB0(int a1)
{
    char* v1;               // eax
    Module* v3;             // [esp+4Ch] [ebp-32Ch]
    char Src;               // [esp+50h] [ebp-328h]
    int v5;                 // [esp+150h] [ebp-228h]
    char Dest;              // [esp+154h] [ebp-224h]
    HMENU hMenu;            // [esp+254h] [ebp-124h]
    HMENU v8;               // [esp+258h] [ebp-120h]
    int v9;                 // [esp+25Ch] [ebp-11Ch]
    struct _finddata_t v10; // [esp+260h] [ebp-118h]

    v8 = 0;
    if (dword_416AB8)
    {
        hMenu = GetMenu(*(HWND*)(dword_416AB8 + 100));
        if (hMenu)
            v8 = GetSubMenu(hMenu, 0);
    }
    sprintf(&Dest, "%s/*.dll", a1);
    v9 = findfirst(&Dest, &v10);
    LOBYTE(v5) = v9 == -1;
    while (!(_BYTE)v5)
    {
        sprintf(&Src, "%s/%s", a1, v10.name);
        v1 = strdup(&Src);
        v3 = ModuleMgr::loadModule(modMgr, v1);
        if (v8)
            Module::menuPlugins(v3, (struct MenuPlugin*)&unk_416638, v8);
        LOBYTE(v5) = findnext(v9, &v10) != 0;
    }
    return findclose(v9);
}
// 416AB8: using guessed type int dword_416AB8;
// 417420: using guessed type void __thiscall Module::menuPlugins(Module *__hidden this, struct MenuPlugin *, HMENU);
// 417424: using guessed type struct Module *__thiscall ModuleMgr::loadModule(ModuleMgr *__hidden this, char *);
// 41747C: using guessed type struct ModuleMgr *modMgr;

//----- (00401FF0) --------------------------------------------------------
UIMgr* __thiscall sub_401FF0(UIMgr* this, char a2)
{
    UIMgr* v3; // [esp+4Ch] [ebp-4h]

    v3 = this;
    UIMgr::~UIMgr(this);
    if (a2 & 1)
        operator delete((void*)v3);
    return v3;
}
// 417428: using guessed type _DWORD __thiscall UIMgr::~UIMgr(UIMgr *__hidden this);

//----- (00402070) --------------------------------------------------------
ModuleMgr* __thiscall sub_402070(ModuleMgr* this, char a2)
{
    ModuleMgr* v3; // [esp+4Ch] [ebp-4h]

    v3 = this;
    ModuleMgr::~ModuleMgr(this);
    if (a2 & 1)
        operator delete((void*)v3);
    return v3;
}
// 41742C: using guessed type _DWORD __thiscall ModuleMgr::~ModuleMgr(ModuleMgr *__hidden this);

//----- (004020F0) --------------------------------------------------------
NodeMgr* __thiscall sub_4020F0(NodeMgr* this, char a2)
{
    NodeMgr* v3; // [esp+4Ch] [ebp-4h]

    v3 = this;
    NodeMgr::~NodeMgr(this);
    if (a2 & 1)
        operator delete((void*)v3);
    return v3;
}
// 417430: using guessed type _DWORD __thiscall NodeMgr::~NodeMgr(NodeMgr *__hidden this);

//----- (004021C0) --------------------------------------------------------
void __cdecl sub_4021C0(float a1)
{
    float v1; // ST54_4

    v1 = sqrt(a1);
}

//----- (00402280) --------------------------------------------------------
_DWORD* __thiscall sub_402280(_DWORD* this)
{
    this[2] = 0;
    return this;
}

//----- (00402700) --------------------------------------------------------
void sub_402700() { ; }

//----- (004038A1) --------------------------------------------------------
int SEH_401510() { return _CxxFrameHandler(); }
// 40247A: using guessed type int _CxxFrameHandler(void);

//----- (004038CB) --------------------------------------------------------
int SEH_401A30() { return _CxxFrameHandler(); }
// 40247A: using guessed type int _CxxFrameHandler(void);

// ALL OK, 20 function(s) have been successfully decompiled
